/**
 * HADI REAL ESTATE — SEED DATASET WITH LEAD SCORING & STAGES
 * - Admin account + 3 Agents
 * - 5 Developers
 * - 6 Off-Plan Projects
 * - 15 Ready Properties
 * - 40 Sample Buyer Leads with scores (HOT, WARM, COLD), stages, and activity dates
 * - 10 Viewings
 * - 5 Completed Sales
 */

const STAFF_LOGINS = [
  {
    id: 1,
    name: 'Hadi (Managing Director)',
    email: 'admin@hadirealestate.ae',
    password_hash: 'Hadi2026!',
    role: 'Admin', // Super Admin: sees all leads, all agents, deals
    phone: '+971 4 800 HADI',
    license_no: 'RERA-ORN-19042',
    bio: 'Founder and Principal Broker overseeing prime UAE portfolio acquisitions and private client fiduciaries.',
    avatar_url: 'assets/images/agent1.jpg',
    monthly_target_aed: 50000000
  },
  {
    id: 2,
    name: 'Rashid Al-Mansoor',
    email: 'rashid@hadirealestate.ae',
    password_hash: 'Rashid2026!',
    role: 'Agent',
    phone: '+971 50 882 1928',
    license_no: 'RERA-BRN-49210',
    bio: 'Over 14 years specializing in ultra-prime beachfront estates on Palm Jumeirah and trophy penthouses in Downtown Dubai.',
    avatar_url: 'assets/images/agent1.jpg',
    monthly_target_aed: 30000000
  },
  {
    id: 3,
    name: 'Elena Rostova',
    email: 'elena@hadirealestate.ae',
    password_hash: 'Elena2026!',
    role: 'Agent',
    phone: '+971 52 449 8102',
    license_no: 'RERA-BRN-53108',
    bio: 'Expert in high-yield off-plan portfolios, structured cross-border wealth management, and private European family offices.',
    avatar_url: 'assets/images/agent2.jpg',
    monthly_target_aed: 25000000
  },
  {
    id: 4,
    name: 'Tariq Al-Hashimi',
    email: 'tariq@hadirealestate.ae',
    password_hash: 'Tariq2026!',
    role: 'Agent',
    phone: '+971 55 918 3477',
    license_no: 'RERA-BRN-61842',
    bio: 'Specialist in early-stage institutional off-plan acquisitions across Dubai Hills Estate and Business Bay.',
    avatar_url: 'assets/images/agent3.jpg',
    monthly_target_aed: 20000000
  }
];

const DEVELOPERS = [
  {
    id: 1,
    name: 'Aura Luxe Developments',
    slug: 'aura-luxe',
    origin: 'Dubai, UAE',
    established_year: 2014,
    description: 'Boutique architectural master developer renowned for sculptural organic facades, private plunge pools, and bespoke Italian interior finishes.',
    track_record_value_aed: 7800000000,
    completed_projects_count: 14
  },
  {
    id: 2,
    name: 'Elysian Living UAE',
    slug: 'elysian-living',
    origin: 'Dubai, UAE',
    established_year: 2011,
    description: 'Pioneers of coastal private island sanctuaries, cantilevered beachfront villas, and marina horizon towers across the Arabian Gulf.',
    track_record_value_aed: 12500000000,
    completed_projects_count: 22
  },
  {
    id: 3,
    name: 'Mirage Heights Development',
    slug: 'mirage-heights',
    origin: 'Dubai, UAE',
    established_year: 2016,
    description: 'High-rise architectural innovator specializing in ultra-luxury vertical sky mansions, double-height terraces, and panoramic city skylines.',
    track_record_value_aed: 9200000000,
    completed_projects_count: 16
  },
  {
    id: 4,
    name: 'Aethelgard Real Estate',
    slug: 'aethelgard',
    origin: 'Abu Dhabi & Dubai, UAE',
    established_year: 2009,
    description: 'Branded luxury sanctuary estates that blend desert oasis tranquility with championship golf course vistas and low-density layouts.',
    track_record_value_aed: 15400000000,
    completed_projects_count: 29
  },
  {
    id: 5,
    name: 'Solaria Crest Properties',
    slug: 'solaria-crest',
    origin: 'Dubai, UAE',
    established_year: 2018,
    description: 'Sustainable biophilic master developer focusing on urban wellness, smart home ecosystems, and high-yield residential communities.',
    track_record_value_aed: 4600000000,
    completed_projects_count: 11
  }
];

const OFFPLAN_PROJECTS = [
  {
    id: 1,
    name: 'Celeste Tower Residences',
    slug: 'celeste-tower',
    developer_id: 3,
    developer_name: 'Mirage Heights Development',
    community: 'Downtown Dubai',
    starting_price_aed: 4800000,
    handover_date: 'Q4 2027',
    payment_plan_summary: '70/30 Payment Plan (20% Down Payment)',
    payment_plan_breakdown: [
      { milestone: 'On Booking', percent: 20 },
      { milestone: 'During Construction (5 Milestones)', percent: 50 },
      { milestone: 'On Key Handover (Q4 2027)', percent: 30 }
    ],
    roi_projected: '9.2% Net Expected Yield',
    property_types: '1, 2, 3 & 4 Bedroom Sky Suites',
    description: 'A 50-storey sculptural residential icon standing proudly in central Downtown Dubai. Features cantilevered sky gardens, private resident infinity pool suspended over the city, and Italian marble finishes.',
    features: [
      'Unobstructed Downtown Skyline Views',
      'Cantilevered Sky Gardens',
      'Private Resident Club & Cigar Lounge',
      'Smart Climate & Lighting Automation Suite',
      'VIP Valet & 24/7 Concierge'
    ],
    brochure_filename: 'celeste-tower-brochure.pdf',
    hero_image: 'assets/images/celeste-tower.jpg',
    gallery_images: [
      'assets/images/celeste-tower.jpg',
      'assets/images/downtown-penthouse.jpg'
    ],
    is_featured: true
  },
  {
    id: 2,
    name: 'The Palm Horizon Residences',
    slug: 'palm-horizon',
    developer_id: 2,
    developer_name: 'Elysian Living UAE',
    community: 'Palm Jumeirah',
    starting_price_aed: 16500000,
    handover_date: 'Q2 2028',
    payment_plan_summary: '60/40 Construction Linked (20% Down Payment)',
    payment_plan_breakdown: [
      { milestone: 'Down Payment on Booking', percent: 20 },
      { milestone: 'Construction Linked (4 Installments)', percent: 40 },
      { milestone: 'Upon Handover (Q2 2028)', percent: 40 }
    ],
    roi_projected: '8.4% Net Expected Yield',
    property_types: '3, 4 & 5 Bedroom Waterfront Penthouses',
    description: 'Exclusive lagoon-front living with private beach access, personal yacht marina berths, and expansive sunset-oriented terraces overlooking the Arabian Gulf.',
    features: [
      'Private Frond Lagoon Access',
      'Yacht Slip Access',
      'Double Height Glass Living Salons',
      'Private Plunge Pool on Every Terrace',
      'Dedicated Wellness Sanctuary & Spa'
    ],
    brochure_filename: 'palm-horizon-brochure.pdf',
    hero_image: 'assets/images/palm-villa.jpg',
    gallery_images: [
      'assets/images/palm-villa.jpg',
      'assets/images/hero-skyline.jpg'
    ],
    is_featured: true
  },
  {
    id: 3,
    name: 'Serenity Reserve Mansions',
    slug: 'serenity-reserve',
    developer_id: 4,
    developer_name: 'Aethelgard Real Estate',
    community: 'Dubai Hills Estate',
    starting_price_aed: 24000000,
    handover_date: 'Q1 2027',
    payment_plan_summary: '80/20 Flexible Milestone Plan',
    payment_plan_breakdown: [
      { milestone: 'Immediate Booking', percent: 20 },
      { milestone: 'During Structural Construction', percent: 60 },
      { milestone: 'Upon Handover', percent: 20 }
    ],
    roi_projected: '7.8% Capital Appreciation',
    property_types: '5, 6 & 7 Bedroom Forest Mansions',
    description: 'Discreet luxury amidst lush landscaped green fairways. Minimalist travertine architecture featuring reflection pools, internal Japanese bonsai courtyards, and underground 6-car galleries.',
    features: [
      'Direct Championship Golf Course Views',
      'Subterranean 6-Car Collector Showroom',
      'Private Cinema & Temperature Wine Cellar',
      'LEED Gold Sustainable Engineering'
    ],
    brochure_filename: 'serenity-reserve-brochure.pdf',
    hero_image: 'assets/images/hills-mansion.jpg',
    gallery_images: [
      'assets/images/hills-mansion.jpg',
      'assets/images/estate-sanctuary.jpg'
    ],
    is_featured: true
  },
  {
    id: 4,
    name: 'Marina Solis Residences',
    slug: 'marina-solis',
    developer_id: 1,
    developer_name: 'Aura Luxe Developments',
    community: 'Dubai Marina',
    starting_price_aed: 3200000,
    handover_date: 'Q3 2026',
    payment_plan_summary: '50/50 Handover Plan',
    payment_plan_breakdown: [
      { milestone: 'Deposit on Booking', percent: 15 },
      { milestone: 'During Construction', percent: 35 },
      { milestone: 'On Handover (Q3 2026)', percent: 50 }
    ],
    roi_projected: '9.6% Net Expected Yield',
    property_types: '1, 2 & 3 Bedroom Waterfront Suites',
    description: 'Sleek waterfront residences steps from the Dubai Marina promenade and yacht club, delivering premier short-term and long-term rental yields.',
    features: [
      'Direct Promenade & Marina Walk Access',
      'Infinity Pool Overlooking Superyachts',
      'Fully Fitted Miele Designer Kitchens',
      'High Projected Capital Gain'
    ],
    brochure_filename: 'marina-solis-brochure.pdf',
    hero_image: 'assets/images/waterfront-residence.jpg',
    gallery_images: [
      'assets/images/waterfront-residence.jpg',
      'assets/images/hero-skyline.jpg'
    ],
    is_featured: false
  },
  {
    id: 5,
    name: 'Verdant Crest Terraces',
    slug: 'verdant-crest',
    developer_id: 5,
    developer_name: 'Solaria Crest Properties',
    community: 'Jumeirah Village Circle (JVC)',
    starting_price_aed: 1250000,
    handover_date: 'Q4 2026',
    payment_plan_summary: '60/40 Post-Handover Friendly Plan',
    payment_plan_breakdown: [
      { milestone: 'Booking Fee', percent: 10 },
      { milestone: 'During Construction (Monthly 1%)', percent: 50 },
      { milestone: 'On Handover', percent: 40 }
    ],
    roi_projected: '10.2% Net Expected Yield',
    property_types: 'Studio, 1 & 2 Bedroom Boutique Terraces',
    description: 'Urban biophilic living in Dubai’s highest-demand rental enclave. Rooftop co-working lounges, hydroponic gardens, and private plunge pool terraces.',
    features: [
      'Top-Performing Rental Yield Location',
      'Rooftop Wellness Club & Infinity Pool',
      'Smart Keyless Access & Home Tech',
      'Turnkey Designer Furniture Packages Available'
    ],
    brochure_filename: 'verdant-crest-brochure.pdf',
    hero_image: 'assets/images/estate-sanctuary.jpg',
    gallery_images: [
      'assets/images/estate-sanctuary.jpg'
    ],
    is_featured: false
  },
  {
    id: 6,
    name: 'Canal Edge Executive Suites',
    slug: 'canal-edge',
    developer_id: 3,
    developer_name: 'Mirage Heights Development',
    community: 'Business Bay',
    starting_price_aed: 2100000,
    handover_date: 'Q2 2027',
    payment_plan_summary: '70/30 Linked Payment Plan',
    payment_plan_breakdown: [
      { milestone: 'Booking Deposit', percent: 20 },
      { milestone: 'During Construction', percent: 50 },
      { milestone: 'Upon Handover', percent: 30 }
    ],
    roi_projected: '8.9% Net Expected Yield',
    property_types: '1 & 2 Bedroom Luxury Canal Suites',
    description: 'Perched on the waterfront curve of Dubai Water Canal, offering seamless connectivity to Downtown Dubai and DIFC financial center.',
    features: [
      'Dubai Water Canal Frontage',
      '5 Minutes to Downtown Dubai & Dubai Mall',
      'Executive Lounge & Private Meeting Pods',
      'High Demand for Corporate Expats'
    ],
    brochure_filename: 'canal-edge-brochure.pdf',
    hero_image: 'assets/images/downtown-penthouse.jpg',
    gallery_images: [
      'assets/images/downtown-penthouse.jpg'
    ],
    is_featured: false
  }
];

const PROPERTIES = [
  // DUBAI MARINA (3)
  {
    id: 1,
    title: 'Marina Crown Sky Villa',
    slug: 'marina-crown-sky-villa',
    community: 'Dubai Marina',
    property_type: 'Duplex Penthouse',
    price_aed: 14200000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 4800,
    description: 'Spectacular two-level duplex sky residence offering sweeping vistas of the marina waterway and luxury superyachts. Features Italian Calacatta marble, private sky pool terrace, double-height living salon, and private elevator.',
    features: ['Direct Marina Views', 'Private Sky Pool', 'Double Height Ceilings', '2 Private Parking Bays', 'Fully Upgraded Interiors'],
    image: 'assets/images/waterfront-residence.jpg',
    gallery_images: ['assets/images/waterfront-residence.jpg', 'assets/images/hero-skyline.jpg'],
    is_ready: true,
    is_featured: true,
    is_sold: false,
    assigned_agent_id: 2
  },
  {
    id: 2,
    title: 'Pier Point Luxury Duplex',
    slug: 'pier-point-luxury-duplex',
    community: 'Dubai Marina',
    property_type: 'Apartment',
    price_aed: 6850000,
    bedrooms: 3,
    bathrooms: 4,
    sqft: 2650,
    description: 'Immaculately upgraded corner residence right on the Marina promenade. Floor-to-ceiling glass wrapping around all bedrooms, chef prep kitchen, and high rental return potential.',
    features: ['Corner Unit', 'Wrap-around Balcony', 'Smart Home System', 'Walk to Marina Mall', 'Direct Yacht Club Access'],
    image: 'assets/images/waterfront-residence.jpg',
    gallery_images: ['assets/images/waterfront-residence.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: false,
    assigned_agent_id: 3
  },
  {
    id: 3,
    title: 'Azure Horizon Waterfront Residence',
    slug: 'azure-horizon-waterfront',
    community: 'Dubai Marina',
    property_type: 'Apartment',
    price_aed: 4200000,
    bedrooms: 2,
    bathrooms: 3,
    sqft: 1720,
    description: 'Bright high-floor apartment overlooking the entrance of Dubai Harbour and the Marina canal. Tastefully furnished with minimalist Nordic-Italian decor.',
    features: ['High Floor Harbor View', 'Renovated Kitchen', 'Infinity Community Pool', 'Vacant on Transfer'],
    image: 'assets/images/hero-skyline.jpg',
    gallery_images: ['assets/images/hero-skyline.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: false,
    assigned_agent_id: 4
  },

  // DOWNTOWN DUBAI (3)
  {
    id: 4,
    title: 'The Celeste Sky Penthouse',
    slug: 'celeste-sky-penthouse',
    community: 'Downtown Dubai',
    property_type: 'Penthouse',
    price_aed: 34500000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 7850,
    description: 'Commanding uninterrupted 360-degree vistas of the illuminated Burj Khalifa and Dubai Fountain. Double-height ceilings, private rooftop jacuzzi deck, and bespoke champagne lounge.',
    features: ['Full Burj Khalifa Panoramic View', 'Private High-Speed Elevator', 'Rooftop Heated Jacuzzi', 'Bespoke Bar & Lounge', '24/7 Dedicated Valet'],
    image: 'assets/images/downtown-penthouse.jpg',
    gallery_images: ['assets/images/downtown-penthouse.jpg', 'assets/images/hero-skyline.jpg'],
    is_ready: true,
    is_featured: true,
    is_sold: false,
    assigned_agent_id: 2
  },
  {
    id: 5,
    title: 'Opera District Boulevard Suite',
    slug: 'opera-district-boulevard-suite',
    community: 'Downtown Dubai',
    property_type: 'Apartment',
    price_aed: 8900000,
    bedrooms: 3,
    bathrooms: 3,
    sqft: 2340,
    description: 'Situated in the cultural epicenter of Downtown Dubai. Just moments from Dubai Opera, featuring refined parquet flooring, Gaggenau appliances, and fountain views.',
    features: ['Fountain & Opera Views', 'Prime Boulevard Location', 'Gaggenau Fitted Kitchen', 'Residents Lounge & Gym'],
    image: 'assets/images/downtown-penthouse.jpg',
    gallery_images: ['assets/images/downtown-penthouse.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: false,
    assigned_agent_id: 3
  },
  {
    id: 6,
    title: 'Downtown Heights Grand Apartment',
    slug: 'downtown-heights-grand',
    community: 'Downtown Dubai',
    property_type: 'Apartment',
    price_aed: 5400000,
    bedrooms: 2,
    bathrooms: 3,
    sqft: 1680,
    description: 'Generously proportioned luxury two-bedroom residence on a prestigious high floor. Open-concept dining, walk-in Poliform dressing rooms, and concierge service.',
    features: ['High Floor', 'Walk-in Closets', 'En-suite Bedrooms', 'Direct Air-conditioned Mall Connection'],
    image: 'assets/images/downtown-penthouse.jpg',
    gallery_images: ['assets/images/downtown-penthouse.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: false,
    assigned_agent_id: 4
  },

  // PALM JUMEIRAH (3)
  {
    id: 7,
    title: 'The Palm Frond Signature Villa',
    slug: 'palm-frond-signature-villa',
    community: 'Palm Jumeirah',
    property_type: 'Villa',
    price_aed: 48000000,
    bedrooms: 6,
    bathrooms: 7,
    sqft: 11200,
    description: 'An architectural masterwork perched on an exclusive private frond. Features private white-sand beach access, 22-meter infinity pool facing the Dubai skyline, Italian travertine cladding, and floor-to-ceiling panoramic glass walls.',
    features: ['Direct Beachfront Frond', '22-Meter Private Infinity Pool', 'Italian Travertine Cladding', 'Show & Prep Kitchens', 'Staff Quarters'],
    image: 'assets/images/palm-villa.jpg',
    gallery_images: ['assets/images/palm-villa.jpg', 'assets/images/estate-sanctuary.jpg'],
    is_ready: true,
    is_featured: true,
    is_sold: false,
    assigned_agent_id: 2
  },
  {
    id: 8,
    title: 'Crescent Coral Sea Mansion',
    slug: 'crescent-coral-sea-mansion',
    community: 'Palm Jumeirah',
    property_type: 'Villa',
    price_aed: 68000000,
    bedrooms: 7,
    bathrooms: 9,
    sqft: 15400,
    description: 'One of the most prestigious trophy estates on the outer crescent of Palm Jumeirah. Unobstructed open Arabian Gulf sunsets, private boat slipway, spa salon, and manicured private palm oasis.',
    features: ['Sunset Sea Panoramas', 'Private Boat Slipway', 'Private Wellness Spa & Sauna', 'Home Cinema Suite', '8 Car Secure Garage'],
    image: 'assets/images/palm-villa.jpg',
    gallery_images: ['assets/images/palm-villa.jpg'],
    is_ready: true,
    is_featured: true,
    is_sold: false,
    assigned_agent_id: 2
  },
  {
    id: 9,
    title: 'Palm Royal Horizon Penthouse',
    slug: 'palm-royal-horizon-penthouse',
    community: 'Palm Jumeirah',
    property_type: 'Penthouse',
    price_aed: 28000000,
    bedrooms: 4,
    bathrooms: 5,
    sqft: 6200,
    description: 'Ultra-exclusive residential penthouse offering 270-degree perspectives across the Palm fronds and the Dubai Marina skyline. Private cantilevered pool and bespoke millwork.',
    features: ['270-Degree Palm Views', 'Private Cantilevered Pool', 'Full Floor Privacy', 'Beach Club Privileges'],
    image: 'assets/images/palm-villa.jpg',
    gallery_images: ['assets/images/palm-villa.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: true, // Sample sold property
    sold_price_aed: 28000000,
    sold_date: '2026-08-28',
    assigned_agent_id: 3
  },

  // BUSINESS BAY (2)
  {
    id: 10,
    title: 'Canal Vista Executive Residence',
    slug: 'canal-vista-executive',
    community: 'Business Bay',
    property_type: 'Apartment',
    price_aed: 4600000,
    bedrooms: 2,
    bathrooms: 3,
    sqft: 1820,
    description: 'High-end waterfront apartment directly facing the Dubai Water Canal promenade. Floor-to-ceiling acoustic glazing, Italian quartz countertops, and fast transit to DIFC.',
    features: ['Direct Canal View', 'Acoustic Soundproofing', 'Resort Style Pool Deck', 'High Rental Demand Area'],
    image: 'assets/images/waterfront-residence.jpg',
    gallery_images: ['assets/images/waterfront-residence.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: false,
    assigned_agent_id: 4
  },
  {
    id: 11,
    title: 'The Sterling Marquee Duplex',
    slug: 'sterling-marquee-duplex',
    community: 'Business Bay',
    property_type: 'Duplex Penthouse',
    price_aed: 7200000,
    bedrooms: 3,
    bathrooms: 4,
    sqft: 3100,
    description: 'Sensational double-height loft duplex offering a Manhattan architectural feel in central Dubai. Features industrial brass detailing, open staircase, and private terrace.',
    features: ['Double-Height Loft Living', 'Downtown Skyline Background', 'Custom Brass Details', 'Private Terrace'],
    image: 'assets/images/downtown-penthouse.jpg',
    gallery_images: ['assets/images/downtown-penthouse.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: false,
    assigned_agent_id: 3
  },

  // DUBAI HILLS ESTATE (3)
  {
    id: 12,
    title: 'The Oasis Serenity Mansion',
    slug: 'oasis-serenity-mansion',
    community: 'Dubai Hills',
    property_type: 'Villa',
    price_aed: 58000000,
    bedrooms: 7,
    bathrooms: 9,
    sqft: 16500,
    description: 'A discreet architectural sanctuary set directly overlooking championship fairways. Features cascading water reflection courts, private cinema, wellness spa, subterranean 8-car gallery, and sculpted olive tree courtyards.',
    features: ['Championship Golf Course View', 'Private Cinema & Spa', '8-Car Subterranean Gallery', 'Reflection Water Gardens', 'Ultra-Private Plot'],
    image: 'assets/images/hills-mansion.jpg',
    gallery_images: ['assets/images/hills-mansion.jpg', 'assets/images/estate-sanctuary.jpg'],
    is_ready: true,
    is_featured: true,
    is_sold: false,
    assigned_agent_id: 2
  },
  {
    id: 13,
    title: 'Parkside Luxury Family Villa',
    slug: 'parkside-luxury-family-villa',
    community: 'Dubai Hills',
    property_type: 'Villa',
    price_aed: 18500000,
    bedrooms: 5,
    bathrooms: 6,
    sqft: 7200,
    description: 'Contemporary family estate situated on a quiet cul-de-sac adjacent to Dubai Hills Central Park. Expansive backyard with temperature-regulated pool and outdoor barbecue gazebo.',
    features: ['Direct Park Access', 'Private Heated Pool', 'Outdoor Chef Kitchen', 'Separate Maid & Driver Rooms'],
    image: 'assets/images/hills-mansion.jpg',
    gallery_images: ['assets/images/hills-mansion.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: false,
    assigned_agent_id: 3
  },
  {
    id: 14,
    title: 'Fairway Crest Contemporary Villa',
    slug: 'fairway-crest-contemporary',
    community: 'Dubai Hills',
    property_type: 'Villa',
    price_aed: 23000000,
    bedrooms: 5,
    bathrooms: 6,
    sqft: 8600,
    description: 'Sleek minimalist modernist lines designed with warm travertine and dark bronze accents. Overlooks the 14th fairway of Dubai Hills Golf Club.',
    features: ['Direct Fairway Frontage', 'Minimalist Architecture', 'Smart Home Integration', 'Turnkey Condition'],
    image: 'assets/images/hills-mansion.jpg',
    gallery_images: ['assets/images/hills-mansion.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: true,
    sold_price_aed: 23000000,
    sold_date: '2026-09-10',
    assigned_agent_id: 2
  },

  // JVC - JUMEIRAH VILLAGE CIRCLE (1)
  {
    id: 15,
    title: 'Bellevue Garden Penthouse',
    slug: 'bellevue-garden-penthouse-jvc',
    community: 'JVC',
    property_type: 'Penthouse',
    price_aed: 2450000,
    bedrooms: 3,
    bathrooms: 4,
    sqft: 2850,
    description: 'Exceptional top-floor residence in JVC featuring a private landscaped terrace with plunge pool. Ideal entry point into Dubai real estate with 9.8% gross rental yields.',
    features: ['Private Plunge Pool on Terrace', '9.8% Gross Rental Yield', 'Low Service Charges', 'Fully Renovated'],
    image: 'assets/images/estate-sanctuary.jpg',
    gallery_images: ['assets/images/estate-sanctuary.jpg'],
    is_ready: true,
    is_featured: false,
    is_sold: true,
    sold_price_aed: 2450000,
    sold_date: '2026-09-18',
    assigned_agent_id: 4
  }
];

// Helper to generate dates relative to current date (2026-09-29)
const dNow = new Date('2026-09-29T12:00:00Z');
const daysAgo = (days) => new Date(dNow.getTime() - days * 24 * 60 * 60 * 1000).toISOString();

// 40 Sample Buyer Leads with Realistic Scores & Stages
const SAMPLE_LEADS = [
  // HOT LEADS (Score >= 70)
  {
    id: 1,
    full_name: 'Sir Charles Cavendish',
    email: 'c.cavendish@mayfaircapital.co.uk',
    phone: '+44 7700 900142',
    budget_aed: 'AED 35M - 60M',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Beachfront Villa',
    source: 'Property Detail - Book a Viewing',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 95,
    score_label: 'HOT',
    payment_method: 'Cash funds in HSBC Expat',
    timeline: 'Immediate viewing this Thursday',
    specific_property_id: 7,
    specific_property_title: 'The Palm Frond Signature Villa',
    notes: 'Cash buyer. Visiting Dubai next Thursday for frond villa inspection. Pre-cleared security entry.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(0) // Today
  },
  {
    id: 2,
    full_name: 'Sophia Van Der Bilt',
    email: 'sophia.vanderbilt@zurichfamily.ch',
    phone: '+41 79 123 4567',
    budget_aed: 'AED 60M+',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Villa',
    source: 'Property Detail - Enquire Form',
    stage: 'Offer',
    status: 'Offer Made',
    score: 98,
    score_label: 'HOT',
    payment_method: 'Full asking price cash',
    timeline: 'Immediate closing',
    specific_property_id: 8,
    specific_property_title: 'Crescent Coral Sea Mansion',
    notes: 'Written cash offer submitted at AED 66M against asking AED 68M. Ready for contract signing.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(1)
  },
  {
    id: 3,
    full_name: 'Vikram Singhania',
    email: 'v.singhania@apexholding.sg',
    phone: '+65 9123 8841',
    budget_aed: 'AED 30M - 60M',
    preferred_community: 'Downtown Dubai',
    property_type: 'Sky Penthouse',
    source: 'Home Page Register Form',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 88,
    score_label: 'HOT',
    payment_method: 'Cash funds ready',
    timeline: 'Viewing Friday afternoon',
    specific_property_id: 4,
    specific_property_title: 'The Celeste Sky Penthouse',
    notes: 'Looking for full Burj Khalifa view penthouse. Arriving from Singapore on private charter.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(0)
  },
  {
    id: 4,
    full_name: 'Amara Al-Kuwari',
    email: 'amara.kuwari@dohainvest.qa',
    phone: '+974 55 129 034',
    budget_aed: 'AED 60M+',
    preferred_community: 'Dubai Hills',
    property_type: 'Mansion',
    source: 'Direct Partner Desk',
    stage: 'Offer',
    status: 'In Negotiation',
    score: 96,
    score_label: 'HOT',
    payment_method: 'Cash transfer via QNB',
    timeline: 'Ready to sign this month',
    specific_property_id: 12,
    specific_property_title: 'The Oasis Serenity Mansion',
    notes: 'Reviewing Oasis Serenity Mansion title deed with DLD trustee. Structural engineer attending.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(0)
  },
  {
    id: 5,
    full_name: 'Fahad Al-Sulaiman',
    email: 'fahad@riyadhholding.sa',
    phone: '+966 50 123 9876',
    budget_aed: 'AED 30M - 60M',
    preferred_community: 'Dubai Hills',
    property_type: 'Villa',
    source: 'Sell Property Valuation Form',
    stage: 'Offer',
    status: 'Offer Made',
    score: 92,
    score_label: 'HOT',
    payment_method: 'Own cash funds',
    timeline: 'Immediate settlement',
    specific_property_id: 14,
    specific_property_title: 'Fairway Crest Contemporary Villa',
    notes: 'Submitted formal written offer on Fairway Crest Villa. Family office transfer.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(1)
  },
  {
    id: 6,
    full_name: 'Oliver Sterling',
    email: 'oliver@sterlingwealth.co.uk',
    phone: '+44 7800 123987',
    budget_aed: 'AED 30M - 60M',
    preferred_community: 'Downtown Dubai',
    property_type: 'Sky Penthouse',
    source: 'Property Detail - Book a Viewing',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 85,
    score_label: 'HOT',
    payment_method: 'Barclays Private Bank transfer',
    timeline: 'Viewing Friday 5 PM',
    specific_property_id: 4,
    specific_property_title: 'The Celeste Sky Penthouse',
    notes: 'Access to rooftop terrace and private elevator foyer confirmed with building concierge.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(0)
  },
  {
    id: 7,
    full_name: 'Zaid Al-Basha',
    email: 'zaid@kuwaitoilcorp.kw',
    phone: '+965 99 887766',
    budget_aed: 'AED 60M+',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Villa',
    source: 'VIP Modal Register Form',
    stage: 'Offer',
    status: 'Offer Made',
    score: 94,
    score_label: 'HOT',
    payment_method: 'Full cash payment',
    timeline: 'Within 2 weeks',
    specific_property_id: 8,
    specific_property_title: 'Crescent Coral Sea Mansion',
    notes: 'Formal letter of intent submitted. Escrow deposit draft prepared.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(2)
  },
  {
    id: 8,
    full_name: 'Benjamin Rothschild',
    email: 'b.rothschild@londontrust.co.uk',
    phone: '+44 7900 887766',
    budget_aed: 'AED 60M+',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Signature Villa',
    source: 'Executive VIP Desk',
    stage: 'Won',
    status: 'Closed Won',
    score: 100,
    score_label: 'HOT',
    payment_method: 'Cash Escrow',
    timeline: 'Completed',
    specific_property_id: 7,
    specific_property_title: 'The Palm Frond Signature Villa',
    notes: 'Transaction completed. Title deed registered at Dubai Land Department. 2% broker commission paid.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(5)
  },
  {
    id: 9,
    full_name: 'Sultan Al-Kaabi',
    email: 'sultan@alainroyal.ae',
    phone: '+971 50 999 8811',
    budget_aed: 'AED 30M - 60M',
    preferred_community: 'Dubai Hills',
    property_type: 'Villa',
    source: 'Contact Page Form',
    stage: 'Won',
    status: 'Closed Won',
    score: 100,
    score_label: 'HOT',
    payment_method: 'Cash Manager Cheque',
    timeline: 'Completed',
    specific_property_id: 14,
    specific_property_title: 'Fairway Crest Contemporary Villa',
    notes: 'Completed purchase on Fairway Crest Villa for AED 23,000,000.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(8)
  },
  {
    id: 10,
    full_name: 'Hassan Bin Rashid Al-Thani',
    email: 'hassan.al-thani@capitalholdings.com',
    phone: '+971 55 234 5678',
    budget_aed: 'AED 60M+',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Villa',
    source: 'Executive VIP Referral',
    stage: 'Won',
    status: 'Closed Won',
    score: 100,
    score_label: 'HOT',
    payment_method: 'Wire Transfer Escrow',
    timeline: 'Completed',
    specific_property_id: 7,
    specific_property_title: 'The Palm Frond Signature Villa Frond G',
    notes: 'Purchased signature frond villa for AED 52M. Commission settled.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(7)
  },

  // WARM LEADS (Score 40 - 69)
  {
    id: 11,
    full_name: 'Dr. Tariq Mansoor',
    email: 'tariq.mansoor@consultant.ae',
    phone: '+971 50 491 8234',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Dubai Hills',
    property_type: 'Villa',
    source: 'Home Page Register Form',
    stage: 'Contacted',
    status: 'Contacted',
    score: 65,
    score_label: 'WARM',
    payment_method: '50% Cash + 50% Bank Loan',
    timeline: 'Within 2 months',
    specific_property_id: 13,
    specific_property_title: 'Parkside Luxury Family Villa',
    notes: 'Relocating family from Geneva. Needs 5+ beds close to King’s College Hospital & Dubai Hills Mall.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(1)
  },
  {
    id: 12,
    full_name: 'Jean-Luc Moreau',
    email: 'jl.moreau@monacoprivate.mc',
    phone: '+377 93 10 20 30',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Penthouse',
    source: 'Off-Plan - Download Brochure',
    stage: 'Contacted',
    status: 'Contacted',
    score: 68,
    score_label: 'WARM',
    payment_method: '60/40 Construction milestones',
    timeline: 'Q1 2027 entry',
    specific_property_id: null,
    specific_property_title: 'The Palm Horizon Residences',
    notes: 'Downloaded Palm Horizon brochure. Requested Zoom consultation on tax residency in UAE.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(2)
  },
  {
    id: 13,
    full_name: 'Elena Mikhailova',
    email: 'elena.mikhailova@investpartners.ae',
    phone: '+971 52 837 1920',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Downtown Dubai',
    property_type: 'Apartment',
    source: 'Mortgage Calculator Advisory Form',
    stage: 'Contacted',
    status: 'Contacted',
    score: 62,
    score_label: 'WARM',
    payment_method: 'Mortgage pre-approved ADCB',
    timeline: 'Ready within 30 days',
    specific_property_id: 5,
    specific_property_title: 'Opera District Boulevard Suite',
    notes: 'Pre-approved for AED 8M mortgage through ADCB. Viewing Opera District suites.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(1)
  },
  {
    id: 14,
    full_name: 'Kavita Patel',
    email: 'kavita.patel@mumbaifinance.in',
    phone: '+91 98200 45123',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Dubai Hills',
    property_type: 'Villa',
    source: 'Property Detail - Book a Viewing',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 68,
    score_label: 'WARM',
    payment_method: 'Self-funded wire',
    timeline: 'Viewing next Wednesday',
    specific_property_id: 13,
    specific_property_title: 'Parkside Luxury Family Villa',
    notes: 'Requested private viewing for Parkside Villa. School proximity essential.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(1)
  },
  {
    id: 15,
    full_name: 'Arthur Pendelton',
    email: 'arthur@pendelton-estates.com',
    phone: '+44 7911 829301',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Dubai Marina',
    property_type: 'Duplex Penthouse',
    source: 'Floating Call Me Back Modal',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 66,
    score_label: 'WARM',
    payment_method: 'Own corporate fund',
    timeline: 'Next week',
    specific_property_id: 1,
    specific_property_title: 'Marina Crown Sky Villa',
    notes: 'Wants yacht berth dimensions and bridge clearance details before putting in offer.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(0)
  },
  {
    id: 16,
    full_name: 'Nathalie Dupont',
    email: 'nathalie.dupont@luxeparis.fr',
    phone: '+33 6 12 34 56 78',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Downtown Dubai',
    property_type: 'Apartment',
    source: 'Property Detail - Enquire Form',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 64,
    score_label: 'WARM',
    payment_method: 'Cash via BNP Paribas',
    timeline: 'Viewing this Sunday',
    specific_property_id: 5,
    specific_property_title: 'Opera District Boulevard Suite',
    notes: 'Opera District 3-bed preference. Evening fountain show preview scheduled.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(2)
  },
  {
    id: 17,
    full_name: 'Yusuf Al-Ghamdi',
    email: 'yusuf@jeddahinvest.com',
    phone: '+966 55 987 6543',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Penthouse',
    source: 'Off-Plan - Download Brochure',
    stage: 'Contacted',
    status: 'Contacted',
    score: 67,
    score_label: 'WARM',
    payment_method: 'Saudi Fransi Wire',
    timeline: 'Q4 2026',
    specific_property_id: null,
    specific_property_title: 'The Palm Horizon Residences',
    notes: 'Reviewing Palm Horizon payment plan and private lagoon specs.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(2)
  },
  {
    id: 18,
    full_name: 'Dmitri Voronin',
    email: 'dmitri@cyprusinvest.eu',
    phone: '+357 99 123456',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Apartment',
    source: 'VIP Modal Register Form',
    stage: 'Contacted',
    status: 'Contacted',
    score: 69,
    score_label: 'WARM',
    payment_method: 'Cash buyer ready',
    timeline: 'Ready within 60 days',
    specific_property_id: null,
    specific_property_title: 'Palm Jumeirah Residences',
    notes: 'Cash buyer, immediate transfer for sea view luxury apartment.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(1)
  },
  {
    id: 19,
    full_name: 'Fatima Al-Nuaimi',
    email: 'fatima@sharjahfamily.ae',
    phone: '+971 50 334 1122',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Dubai Hills',
    property_type: 'Villa',
    source: 'Sell Property Valuation Form',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 65,
    score_label: 'WARM',
    payment_method: 'Sale of current asset + cash',
    timeline: 'Upcoming month',
    specific_property_id: 13,
    specific_property_title: 'Parkside Luxury Family Villa',
    notes: 'Upgrading from family villa in Sharjah. Requested inspection.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(1)
  },
  {
    id: 20,
    full_name: 'George Henderson',
    email: 'george@scotgold.co.uk',
    phone: '+44 7920 445566',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Dubai Hills',
    property_type: 'Villa',
    source: 'Off-Plan - Download Brochure',
    stage: 'Contacted',
    status: 'Contacted',
    score: 62,
    score_label: 'WARM',
    payment_method: 'Structured milestones',
    timeline: '2027 handover',
    specific_property_id: null,
    specific_property_title: 'Serenity Reserve Mansions',
    notes: 'Inquired about Serenity Reserve handover and golf membership package.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(2)
  },
  {
    id: 21,
    full_name: 'Claire Beauchamp',
    email: 'claire@genevaprivate.ch',
    phone: '+41 78 889 0011',
    budget_aed: 'AED 35M - 75M',
    preferred_community: 'Downtown Dubai',
    property_type: 'Penthouse',
    source: 'Contact Page Form',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 69,
    score_label: 'WARM',
    payment_method: 'Pictet Bank Wire',
    timeline: 'Arrival this Saturday',
    specific_property_id: 4,
    specific_property_title: 'The Celeste Sky Penthouse',
    notes: 'Private flight arrival Saturday morning. Chauffeur transfer to Downtown requested.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(1)
  },
  {
    id: 22,
    full_name: 'Mona Al-Mansoori',
    email: 'mona.m@adnocfamily.ae',
    phone: '+971 50 112 2334',
    budget_aed: 'AED 35M - 75M',
    preferred_community: 'Dubai Hills',
    property_type: 'Mansion',
    source: 'Home Page Register Form',
    stage: 'Viewing',
    status: 'Viewing Scheduled',
    score: 68,
    score_label: 'WARM',
    payment_method: 'Cash bank check',
    timeline: 'Viewing next Thursday',
    specific_property_id: 12,
    specific_property_title: 'The Oasis Serenity Mansion',
    notes: 'Wants to view Fairway Crest and Oasis Serenity. Private family tour.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(2)
  },
  {
    id: 23,
    full_name: 'Tanya Romanova',
    email: 'tanya@monacoyachts.mc',
    phone: '+377 97 70 80 90',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Palm Jumeirah',
    property_type: 'Penthouse',
    source: 'Property Detail - Enquire Form',
    stage: 'Won',
    status: 'Closed Won',
    score: 100,
    score_label: 'HOT',
    payment_method: 'Cash Funds',
    timeline: 'Completed',
    specific_property_id: 9,
    specific_property_title: 'Palm Royal Horizon Penthouse',
    notes: 'Closed sale on Palm Royal Horizon penthouse for AED 28,000,000. Commission paid.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(10)
  },
  {
    id: 24,
    full_name: 'Ananya Sharma',
    email: 'ananya@delhitech.in',
    phone: '+91 99100 23456',
    budget_aed: 'AED 2M - 5M',
    preferred_community: 'JVC',
    property_type: 'Penthouse',
    source: 'Home Page Register Form',
    stage: 'Won',
    status: 'Closed Won',
    score: 100,
    score_label: 'HOT',
    payment_method: 'Cash Transfer',
    timeline: 'Completed',
    specific_property_id: 15,
    specific_property_title: 'Bellevue Garden Penthouse',
    notes: 'Purchased Bellevue Garden Penthouse JVC for AED 2,450,000.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(11)
  },

  // STALE LEADS (NO ACTIVITY FOR 3+ DAYS - TEST DATA FOR INACTIVITY FILTER)
  {
    id: 25,
    full_name: 'William Montgomery',
    email: 'w.montgomery@nycfamily.com',
    phone: '+1 212 555 0199',
    budget_aed: 'AED 60M+',
    preferred_community: 'Dubai Hills',
    property_type: 'Mansion',
    source: 'VIP Modal Register Form',
    stage: 'Contacted',
    status: 'Awaiting Follow-up',
    score: 74,
    score_label: 'HOT',
    payment_method: 'JPMorgan private wire',
    timeline: 'Late 2026',
    specific_property_id: 12,
    specific_property_title: 'The Oasis Serenity Mansion',
    notes: 'Initial call completed 4 days ago. Has not responded to villa specification sheet.',
    assigned_agent_id: 2,
    assigned_agent_name: 'Rashid Al-Mansoor',
    last_activity_at: daysAgo(4) // 4 days ago -> Stale!
  },
  {
    id: 26,
    full_name: 'Aisha Al-Falasi',
    email: 'aisha.f@dubaigov.ae',
    phone: '+971 55 778 8990',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Dubai Hills',
    property_type: 'Villa',
    source: 'Sell Property Valuation Form',
    stage: 'New',
    status: 'Pending Contact',
    score: 62,
    score_label: 'WARM',
    payment_method: 'Cash',
    timeline: 'Q1',
    specific_property_id: null,
    specific_property_title: 'Dubai Hills Villa',
    notes: 'Requested property valuation 5 days ago. No broker has called back yet.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(5) // 5 days ago -> Stale!
  },
  {
    id: 27,
    full_name: 'Saad Al-Khatib',
    email: 'saad@ammanholding.jo',
    phone: '+962 79 555 4433',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Downtown Dubai',
    property_type: 'Apartment',
    source: 'Property Detail - Enquire Form',
    stage: 'Contacted',
    status: 'Follow-up Due',
    score: 55,
    score_label: 'WARM',
    payment_method: 'Cash',
    timeline: 'Exploring',
    specific_property_id: 5,
    specific_property_title: 'Opera District Boulevard Suite',
    notes: 'Sent brochure 6 days ago. Needs urgent follow-up on pricing flexibility.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(6) // 6 days ago -> Stale!
  },
  {
    id: 28,
    full_name: 'Grace Kim',
    email: 'grace.kim@seoulbio.kr',
    phone: '+82 10 1234 5678',
    budget_aed: 'AED 15M - 35M',
    preferred_community: 'Downtown Dubai',
    property_type: 'Sky Penthouse',
    source: 'Home Page Register Form',
    stage: 'New',
    status: 'Unassigned',
    score: 60,
    score_label: 'WARM',
    payment_method: 'Funds in Shinhan Bank',
    timeline: 'Spring',
    specific_property_id: null,
    specific_property_title: 'Downtown Dubai',
    notes: 'Registered interest 4 days ago. Burj Khalifa view requirement.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(4) // 4 days ago -> Stale!
  },
  {
    id: 29,
    full_name: 'Ibrahim Al-Sayed',
    email: 'ibrahim@cairoproperties.eg',
    phone: '+20 100 123 4567',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Dubai Marina',
    property_type: 'Apartment',
    source: 'Property Detail - Enquire Form',
    stage: 'Contacted',
    status: 'Follow-up Overdue',
    score: 58,
    score_label: 'WARM',
    payment_method: 'Cash wire',
    timeline: 'Soon',
    specific_property_id: 2,
    specific_property_title: 'Pier Point Luxury Duplex',
    notes: 'Last contacted 5 days ago. Looking to purchase 2 apartments in Marina for rental yield.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(5) // 5 days ago -> Stale!
  },
  {
    id: 30,
    full_name: 'Mateo Hernandez',
    email: 'mateo@madridfund.es',
    phone: '+34 600 123 456',
    budget_aed: 'AED 2M - 5M',
    preferred_community: 'JVC',
    property_type: 'Terrace',
    source: 'Off-Plan - Download Brochure',
    stage: 'New',
    status: 'Uncontacted',
    score: 45,
    score_label: 'WARM',
    payment_method: 'Post-handover plan',
    timeline: 'Q4 2026',
    specific_property_id: null,
    specific_property_title: 'Verdant Crest Terraces',
    notes: 'Inquired about Verdant Crest post-handover plan 7 days ago. No activity recorded.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(7) // 7 days ago -> Stale!
  },

  // COLD LEADS (Score < 40)
  {
    id: 31,
    full_name: 'Maximilian Krause',
    email: 'm.krause@berlintech.de',
    phone: '+49 171 8920112',
    budget_aed: 'AED 2M - 5M',
    preferred_community: 'Dubai Marina',
    property_type: 'Waterfront Duplex',
    source: 'Floating WhatsApp Click',
    stage: 'New',
    status: 'New Inquiry',
    score: 35,
    score_label: 'COLD',
    payment_method: 'Unspecified',
    timeline: 'Just browsing / Next year',
    specific_property_id: null,
    specific_property_title: 'General Marina Inquiry',
    notes: 'Casually exploring short-term holiday rental yield potential.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(0)
  },
  {
    id: 32,
    full_name: 'David O’Connor',
    email: 'doconnor@dublinadvisory.ie',
    phone: '+353 87 234 9102',
    budget_aed: 'AED 2M - 5M',
    preferred_community: 'Business Bay',
    property_type: 'Apartment',
    source: 'Home Page Register Form',
    stage: 'New',
    status: 'New Inquiry',
    score: 38,
    score_label: 'COLD',
    payment_method: 'Mortgage inquiry',
    timeline: 'Looking for 2027',
    specific_property_id: null,
    specific_property_title: 'Business Bay',
    notes: 'Inquired regarding UAE Golden Visa minimum investment thresholds.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(0)
  },
  {
    id: 33,
    full_name: 'Lucas Rossi',
    email: 'l.rossi@milanoarchitecture.it',
    phone: '+39 340 1234567',
    budget_aed: 'AED 2M - 5M',
    preferred_community: 'JVC',
    property_type: 'Penthouse',
    source: 'Off-Plan - Download Brochure',
    stage: 'Contacted',
    status: 'Contacted',
    score: 36,
    score_label: 'COLD',
    payment_method: 'Small installments',
    timeline: 'Long term',
    specific_property_id: null,
    specific_property_title: 'JVC Off-Plan',
    notes: 'Architect seeking 2 boutique units in JVC for passive portfolio yield.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(1)
  },
  {
    id: 34,
    full_name: 'Chloe Tremblay',
    email: 'chloe@montrealcapital.ca',
    phone: '+1 514 890 1234',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Business Bay',
    property_type: 'Duplex',
    source: 'Home Page Search Form',
    stage: 'New',
    status: 'New Inquiry',
    score: 38,
    score_label: 'COLD',
    payment_method: 'Unknown',
    timeline: 'Late 2027',
    specific_property_id: null,
    specific_property_title: 'Business Bay',
    notes: 'Wants canal-facing 3-bedroom once business expansion is complete.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(0)
  },
  {
    id: 35,
    full_name: 'Sebastian Weber',
    email: 's.weber@frankfurtbank.de',
    phone: '+49 160 9988776',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Dubai Marina',
    property_type: 'Apartment',
    source: 'Mortgage Calculator Advisory Form',
    stage: 'Lost',
    status: 'Closed Lost',
    score: 30,
    score_label: 'COLD',
    payment_method: 'Denied loan',
    timeline: 'Postponed',
    specific_property_id: 3,
    specific_property_title: 'Azure Horizon Waterfront Residence',
    notes: 'Client decided to postpone purchase due to European banking reallocation.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(12)
  },
  {
    id: 36,
    full_name: 'Rohan Mehta',
    email: 'rohan.mehta@singaporeventures.sg',
    phone: '+65 8123 9900',
    budget_aed: 'AED 2M - 5M',
    preferred_community: 'Business Bay',
    property_type: 'Apartment',
    source: 'Home Page Register Form',
    stage: 'New',
    status: 'New Inquiry',
    score: 35,
    score_label: 'COLD',
    payment_method: 'Financing',
    timeline: 'Not urgent',
    specific_property_id: null,
    specific_property_title: 'Canal Edge',
    notes: 'Interested in Canal Edge off-plan 2-beds.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(0)
  },
  {
    id: 37,
    full_name: 'Liam Gallagher',
    email: 'liam@manchesterholding.co.uk',
    phone: '+44 7711 009988',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Dubai Marina',
    property_type: 'Apartment',
    source: 'Floating Call Me Back Modal',
    stage: 'Contacted',
    status: 'Contacted',
    score: 39,
    score_label: 'COLD',
    payment_method: 'Property sale in UK pending',
    timeline: 'TBD',
    specific_property_id: null,
    specific_property_title: 'Dubai Marina',
    notes: 'Callback completed. Waiting for Manchester property sale to conclude.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(2)
  },
  {
    id: 38,
    full_name: 'Henrik Lindqvist',
    email: 'henrik@stockholmcapital.se',
    phone: '+46 70 123 4567',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Dubai Marina',
    property_type: 'Duplex',
    source: 'Off-Plan - Download Brochure',
    stage: 'New',
    status: 'New Inquiry',
    score: 34,
    score_label: 'COLD',
    payment_method: 'Unknown',
    timeline: 'General inquiry',
    specific_property_id: null,
    specific_property_title: 'Marina Solis',
    notes: 'Marina Solis brochure downloaded. Follow-up email sent.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(0)
  },
  {
    id: 39,
    full_name: 'Alexander Novak',
    email: 'a.novak@viennawealth.at',
    phone: '+43 664 1234567',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Business Bay',
    property_type: 'Apartment',
    source: 'Mortgage Calculator Advisory Form',
    stage: 'Lost',
    status: 'Closed Lost',
    score: 32,
    score_label: 'COLD',
    payment_method: 'Mortgage',
    timeline: 'Cancelled',
    specific_property_id: null,
    specific_property_title: 'Business Bay',
    notes: 'Selected property in Portugal Golden Visa program instead.',
    assigned_agent_id: 4,
    assigned_agent_name: 'Tariq Al-Hashimi',
    last_activity_at: daysAgo(14)
  },
  {
    id: 40,
    full_name: 'Layla Al-Matrooshi',
    email: 'layla@sharjahlaw.ae',
    phone: '+971 50 665 4433',
    budget_aed: 'AED 5M - 15M',
    preferred_community: 'Downtown Dubai',
    property_type: 'Apartment',
    source: 'Home Page Register Form',
    stage: 'New',
    status: 'New Inquiry',
    score: 36,
    score_label: 'COLD',
    payment_method: 'Unknown',
    timeline: 'Initial research',
    specific_property_id: 6,
    specific_property_title: 'Downtown Heights Grand Apartment',
    notes: 'Inquired about Downtown Heights payment schedules.',
    assigned_agent_id: 3,
    assigned_agent_name: 'Elena Rostova',
    last_activity_at: daysAgo(0)
  }
];

const SAMPLE_VIEWINGS = [
  { id: 1, property_id: 7, property_title: 'The Palm Frond Signature Villa', lead_id: 1, client_name: 'Sir Charles Cavendish', client_phone: '+44 7700 900142', agent_id: 2, agent_name: 'Rashid Al-Mansoor', viewing_date: '2026-10-04', viewing_time: '11:00 AM', status: 'Confirmed', special_requests: 'Private security escort and golf buggy Frond entry requested.' },
  { id: 2, property_id: 4, property_title: 'The Celeste Sky Penthouse', lead_id: 3, client_name: 'Vikram Singhania', client_phone: '+65 9123 8841', agent_id: 2, agent_name: 'Rashid Al-Mansoor', viewing_date: '2026-10-05', viewing_time: '04:30 PM', status: 'Confirmed', special_requests: 'Sunset viewing to verify evening illumination.' },
  { id: 3, property_id: 12, property_title: 'The Oasis Serenity Mansion', lead_id: 4, client_name: 'Amara Al-Kuwari', client_phone: '+974 55 129 034', agent_id: 2, agent_name: 'Rashid Al-Mansoor', viewing_date: '2026-10-06', viewing_time: '02:00 PM', status: 'Confirmed', special_requests: 'Structural engineer attending with client.' },
  { id: 4, property_id: 13, property_title: 'Parkside Luxury Family Villa', lead_id: 14, client_name: 'Kavita Patel', client_phone: '+91 98200 45123', agent_id: 3, agent_name: 'Elena Rostova', viewing_date: '2026-10-07', viewing_time: '10:30 AM', status: 'Confirmed', special_requests: 'Bring school boundary and transport maps.' },
  { id: 5, property_id: 1, property_title: 'Marina Crown Sky Villa', lead_id: 15, client_name: 'Arthur Pendelton', client_phone: '+44 7911 829301', agent_id: 3, agent_name: 'Elena Rostova', viewing_date: '2026-10-07', viewing_time: '03:00 PM', status: 'Confirmed', special_requests: 'Inspect marina berth dimensions.' },
  { id: 6, property_id: 4, property_title: 'The Celeste Sky Penthouse', lead_id: 6, client_name: 'Oliver Sterling', client_phone: '+44 7800 123987', agent_id: 2, agent_name: 'Rashid Al-Mansoor', viewing_date: '2026-10-08', viewing_time: '05:00 PM', status: 'Confirmed', special_requests: 'Access to rooftop terrace and private elevator foyer.' },
  { id: 7, property_id: 14, property_title: 'Fairway Crest Contemporary Villa', lead_id: 22, client_name: 'Mona Al-Mansoori', client_phone: '+971 50 112 2334', agent_id: 3, agent_name: 'Elena Rostova', viewing_date: '2026-10-09', viewing_time: '11:30 AM', status: 'Confirmed', special_requests: 'Family viewing.' },
  { id: 8, property_id: 8, property_title: 'Crescent Coral Sea Mansion', lead_id: 2, client_name: 'Sophia Van Der Bilt', client_phone: '+41 79 123 4567', agent_id: 2, agent_name: 'Rashid Al-Mansoor', viewing_date: '2026-09-24', viewing_time: '04:00 PM', status: 'Completed', special_requests: 'Follow-up offer submitted subsequent to viewing.' },
  { id: 9, property_id: 10, property_title: 'Canal Vista Executive Residence', lead_id: 34, client_name: 'Chloe Tremblay', client_phone: '+1 514 890 1234', agent_id: 4, agent_name: 'Tariq Al-Hashimi', viewing_date: '2026-10-10', viewing_time: '01:00 PM', status: 'Confirmed', special_requests: 'Review canal access and parking.' },
  { id: 10, property_id: 5, property_title: 'Opera District Boulevard Suite', lead_id: 16, client_name: 'Nathalie Dupont', client_phone: '+33 6 12 34 56 78', agent_id: 4, agent_name: 'Tariq Al-Hashimi', viewing_date: '2026-10-11', viewing_time: '06:00 PM', status: 'Confirmed', special_requests: 'Evening fountain show preview.' }
];

const SAMPLE_SALES = [
  { id: 1, property_id: 7, property_name: 'The Palm Frond Signature Villa', lead_id: 8, buyer_name: 'Benjamin Rothschild', agent_id: 2, agent_name: 'Rashid Al-Mansoor', sale_price_aed: 48000000, commission_aed: 960000, closing_date: '2026-08-15', community: 'Palm Jumeirah' },
  { id: 2, property_id: 9, property_name: 'Palm Royal Horizon Penthouse', lead_id: 23, buyer_name: 'Tanya Romanova', agent_id: 3, agent_name: 'Elena Rostova', sale_price_aed: 28000000, commission_aed: 560000, closing_date: '2026-08-28', community: 'Palm Jumeirah' },
  { id: 3, property_id: 14, property_name: 'Fairway Crest Contemporary Villa', lead_id: 9, buyer_name: 'Sultan Al-Kaabi', agent_id: 2, agent_name: 'Rashid Al-Mansoor', sale_price_aed: 23000000, commission_aed: 460000, closing_date: '2026-09-10', community: 'Dubai Hills' },
  { id: 4, property_id: 15, property_name: 'Bellevue Garden Penthouse', lead_id: 24, buyer_name: 'Ananya Sharma', agent_id: 4, agent_name: 'Tariq Al-Hashimi', sale_price_aed: 2450000, commission_aed: 49000, closing_date: '2026-09-18', community: 'JVC' },
  { id: 5, property_id: 7, property_name: 'The Palm Frond Signature Villa Frond G', lead_id: 10, buyer_name: 'Hassan Bin Rashid Al-Thani', agent_id: 2, agent_name: 'Rashid Al-Mansoor', sale_price_aed: 52000000, commission_aed: 1040000, closing_date: '2026-09-22', community: 'Palm Jumeirah' }
];

const SAMPLE_NOTES = [
  { id: 1, lead_id: 1, property_id: 7, author_agent_id: 2, author_name: 'Rashid Al-Mansoor', note_text: 'Client specifically requests sunset-facing fronds on Palm Jumeirah. Funds held in HSBC Expat account.', created_at: daysAgo(0) },
  { id: 2, lead_id: 2, property_id: 8, author_agent_id: 2, author_name: 'Rashid Al-Mansoor', note_text: 'Written offer submitted at AED 66M against asking AED 68M. Seller negotiating on payment timeline.', created_at: daysAgo(1) },
  { id: 3, lead_id: 13, property_id: 5, author_agent_id: 3, author_name: 'Elena Rostova', note_text: 'Mortgage pre-approval received for AED 7.5M from ADCB. Needs 20% equity proof.', created_at: daysAgo(1) },
  { id: 4, lead_id: 3, property_id: 4, author_agent_id: 2, author_name: 'Rashid Al-Mansoor', note_text: 'Client traveling on private flight from Singapore. Confirmed viewing for 4:30 PM.', created_at: daysAgo(0) },
  { id: 5, lead_id: 4, property_id: 12, author_agent_id: 2, author_name: 'Rashid Al-Mansoor', note_text: 'Title deed verification underway with Dubai Land Department. Cash buyer.', created_at: daysAgo(0) }
];

module.exports = {
  STAFF_LOGINS,
  DEVELOPERS,
  OFFPLAN_PROJECTS,
  PROPERTIES,
  SAMPLE_LEADS,
  SAMPLE_VIEWINGS,
  SAMPLE_SALES,
  SAMPLE_NOTES
};
